name = "Claude"
uuid = "a00ee857-659a-4bd1-adc3-7f1f48b9fe16"
authors = ["JaewooJoung <jaewoo.joung@outlook.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1.6"
HTTP = "1.0"
JSON3 = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
